model = "gpt-5"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"

[projects."/data1/huangzhe/code/edge10-quant"]
trust_level = "trusted"

[projects."/data1/huangzhe/code/Synthetic-Video-Pipeline"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.tavily]
command = "npx"
args = ["-y", "tavily-mcp"]
env = { "TAVILY_API_KEY" = "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" }
