site_name: LLM Perf Opt
site_description: Profiling and benchmarking pipeline for DeepSeek‑OCR (Stage 1)
repo_name: llm-perf-opt
repo_url: https://example.invalid/llm-perf-opt

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Running: running.md
  - Artifacts: artifacts.md
  - Visualization: visualization.md
  - Internals: internals.md
  - Analyzer & MFU: analyzer-mfu.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search
