# Unified Hydra defaults (single entrypoint)

defaults:
  # Dataset root and discovery rules
  - dataset: omnidocbench
  # Dataset sampling preset (explicit control of epochs/samples)
  - dataset/sampling@dataset.sampling: default
  # Model architecture + preprocessing defaults (vendor parity)
  - model/deepseek_ocr/arch@model: deepseek_ocr.default
  # Inference defaults (e.g., temperature, max_new_tokens)
  - model/deepseek_ocr/infer@infer: deepseek_ocr.default
  # PyTorch profiler preset (min/default/max) under profiling/torch/
  # Mount under nested key `pipeline.torch_profiler`
  - profiling/torch@pipeline.torch_profiler: torch-profiler.default
  - output/torch@pipeline.torch_profiler.output: default
  - model/deepseek_ocr/output/torch@pipeline.torch_profiler.output.extra.deepseek_ocr: default
  # Nsight presets mounted into nested pipeline keys
  - profiling/nsys@pipeline.nsys: nsys.default
  - profiling/ncu@pipeline.ncu: ncu.default
  - _self_

# Global knobs (basic configuration only)
experiment: stage1
device: cuda:0           # target device
use_flash_attn: true     # enable flash attention if available

# Unified run controls for orchestrator (used by Stage-2/deep profiling)
run:
  mode: deep                   # deep | light
  # DEPRECATED: use dataset.sampling.* overrides in Stage-2 runner instead
  stage1_repeats: 1            # (deprecated) repeats for Stage-1 workload during capture
  dataset_subset_filelist: null # optional filelist to limit workload samples
  top_n_kernels: 30            # number of top kernels to inspect in NCU

# Hydra run/output directory aligns with Stage 1 artifacts by default
hydra:
  run:
    # Default run directory for all pipelines. Individual stages write into
    # subdirectories under this root (e.g., torch_profiler/, static_analysis/, nsys/, ncu/).
    dir: ${hydra:runtime.cwd}/tmp/profile-output/${now:%Y%m%d-%H%M%S}
  output_subdir: null
  job:
    chdir: true

# Unified pipeline configuration
pipeline:
  static_analysis:
    enable: true
    write_reports: true
    use_analytic_fallback: true
    use_synthetic_inputs: true
  # Torch profiler settings are mounted from profiling/torch preset above.
  # Expose a uniform enable flag here; defaults to the preset's 'enabled'.
  torch_profiler:
    enable: ${pipeline.torch_profiler.enabled}
  # Nsight Systems
  nsys:
    enable: false
    gating_nvtx: true
    # Other keys (trace, sample, capture_range, capture_range_end, nvtx_capture)
    # are inherited from the mounted preset.
  # Nsight Compute
  ncu:
    enable: false
    gating_nvtx: true
    # Keys (nvtx_include, set, metrics, sections) inherited from the preset.

# Output controls are now per-pipeline under `pipeline.<stage>.output.*`.
