# Top-level Hydra defaults for Stage 1 profiling

defaults:
  # Dataset root and discovery rules
  - dataset: omnidocbench
  # Model architecture + preprocessing defaults (vendor parity)
  - model/deepseek_ocr/arch@model: deepseek_ocr.default
  # Inference defaults (e.g., temperature, max_new_tokens)
  - model/deepseek_ocr/infer@infer: deepseek_ocr.default
  # PyTorch profiler preset (min/default/max) under profiling/torch/
  # Mount under key `torch_profiler` to avoid confusion with Nsight profiling
  - profiling/torch@torch_profiler: torch-profiler.default
  # Runner configuration (toggle static analysis, etc.)
  - runners: stage1.default
  - _self_

# Global knobs (basic configuration only)
experiment: stage1
repeats: 3               # total rounds to run
device: cuda:0           # target device
use_flash_attn: true     # enable flash attention if available

# Hydra run/output directory aligns with Stage 1 artifacts
hydra:
  run:
    dir: ${hydra:runtime.cwd}/tmp/stage1/${now:%Y%m%d-%H%M%S}
  output_subdir: null
  job:
    chdir: true

# Output controls
outputs:
  save_predictions: false   # save generated text per image for later comparison
  predictions:
    strip_special_tokens: false   # also store a cleaned, human-friendly variant
  visualization:
    enable: true            # write a predictions gallery (Markdown)
    max_images: 16          # limit gallery size (set null for all)
    thumbnail_width: 480    # pixel width for copied thumbnails
