%%{init: {'flowchart': { 'useMaxWidth': false }}}%%
graph LR
  n0["Block @ sam_model.blocks.[0-11] for 12"];
  n1 -->|parfor 1504| n2;
  n3 -->|parfor 2| n4;
  n3 -->|parfor 92| n5;
  n6 -->|parfor 2| n7;
  n6 -->|parfor 2| n8;
  n3 -->|parfor 2| n9;
  n3 -->|parfor 6| n10;
  n11 -->|parfor 2| n12;
  n11 -->|parfor 2| n13;
  n11 -->|parfor 2| n14;
  n15 -->|parfor 2| n16;
  n15 -->|parfor 92| n17;
  n18 -->|parfor 2| n19;
  n18 -->|parfor 2| n20;
  n15 -->|parfor 2| n21;
  n15 -->|parfor 6| n22;
  n23 -->|parfor 2| n24;
  n23 -->|parfor 2| n25;
  n23 -->|parfor 2| n26;
  n27 -->|parfor 2| n28;
  n27 -->|parfor 106| n29;
  n30 -->|parfor 2| n31;
  n30 -->|parfor 2| n32;
  n27 -->|parfor 2| n33;
  n27 -->|parfor 6| n34;
  n35 -->|parfor 2| n36;
  n35 -->|parfor 2| n37;
  n35 -->|parfor 2| n38;
  n39 -->|parfor 2| n40;
  n39 -->|parfor 92| n41;
  n42 -->|parfor 2| n43;
  n42 -->|parfor 2| n44;
  n39 -->|parfor 2| n45;
  n39 -->|parfor 6| n46;
  n47 -->|parfor 2| n48;
  n47 -->|parfor 2| n49;
  n47 -->|parfor 2| n50;
  n51 -->|parfor 2| n52;
  n51 -->|parfor 92| n53;
  n54 -->|parfor 2| n55;
  n54 -->|parfor 2| n56;
  n51 -->|parfor 2| n57;
  n51 -->|parfor 6| n58;
  n59 -->|parfor 2| n60;
  n59 -->|parfor 2| n61;
  n59 -->|parfor 2| n62;
  n63 -->|parfor 2| n64;
  n63 -->|parfor 106| n65;
  n66 -->|parfor 2| n67;
  n66 -->|parfor 2| n68;
  n63 -->|parfor 2| n69;
  n63 -->|parfor 6| n70;
  n71 -->|parfor 2| n72;
  n71 -->|parfor 2| n73;
  n71 -->|parfor 2| n74;
  n75 -->|parfor 2| n76;
  n75 -->|parfor 92| n77;
  n78 -->|parfor 2| n79;
  n78 -->|parfor 2| n80;
  n75 -->|parfor 2| n81;
  n75 -->|parfor 6| n82;
  n83 -->|parfor 2| n84;
  n83 -->|parfor 2| n85;
  n83 -->|parfor 2| n86;
  n87 -->|parfor 2| n88;
  n87 -->|parfor 92| n89;
  n90 -->|parfor 2| n91;
  n90 -->|parfor 2| n92;
  n87 -->|parfor 2| n93;
  n87 -->|parfor 6| n94;
  n95 -->|parfor 2| n96;
  n95 -->|parfor 2| n97;
  n95 -->|parfor 2| n98;
  n99 -->|parfor 2| n100;
  n99 -->|parfor 106| n101;
  n102 -->|parfor 2| n103;
  n102 -->|parfor 2| n104;
  n99 -->|parfor 2| n105;
  n99 -->|parfor 6| n106;
  n107 -->|parfor 2| n108;
  n107 -->|parfor 2| n109;
  n107 -->|parfor 2| n110;
  n111 -->|parfor 2| n112;
  n111 -->|parfor 92| n113;
  n114 -->|parfor 2| n115;
  n114 -->|parfor 2| n116;
  n111 -->|parfor 2| n117;
  n111 -->|parfor 6| n118;
  n119 -->|parfor 2| n120;
  n119 -->|parfor 2| n121;
  n119 -->|parfor 2| n122;
  n123 -->|parfor 2| n124;
  n123 -->|parfor 92| n125;
  n126 -->|parfor 2| n127;
  n126 -->|parfor 2| n128;
  n123 -->|parfor 2| n129;
  n123 -->|parfor 6| n130;
  n131 -->|parfor 2| n132;
  n131 -->|parfor 2| n133;
  n131 -->|parfor 2| n134;
  n135 -->|parfor 2| n136;
  n135 -->|parfor 106| n137;
  n138 -->|parfor 2| n139;
  n138 -->|parfor 2| n140;
  n135 -->|parfor 2| n141;
  n135 -->|parfor 6| n142;
  n143 -->|parfor 2| n144;
  n143 -->|parfor 2| n145;
  n143 -->|parfor 2| n146;
  n147 -->|parfor 4| n148;
  n147 -->|parfor 48| n149;
  n150 -->|parfor 1152| n151;
  n152 -->|parfor 2| n153;
  n152 -->|parfor 30| n154;
  n155 -->|parfor 2| n156;
  n155 -->|parfor 2| n157;
  n152 -->|parfor 2| n158;
  n152 -->|parfor 10| n159;
  n160 -->|parfor 2| n161;
  n160 -->|parfor 2| n162;
  n163 -->|parfor 2| n164;
  n163 -->|parfor 30| n165;
  n166 -->|parfor 2| n167;
  n166 -->|parfor 2| n168;
  n163 -->|parfor 2| n169;
  n163 -->|parfor 10| n170;
  n171 -->|parfor 2| n172;
  n171 -->|parfor 2| n173;
  n174 -->|parfor 2| n175;
  n174 -->|parfor 30| n176;
  n177 -->|parfor 2| n178;
  n177 -->|parfor 2| n179;
  n174 -->|parfor 2| n180;
  n174 -->|parfor 10| n181;
  n182 -->|parfor 2| n183;
  n182 -->|parfor 2| n184;
  n185 -->|parfor 2| n186;
  n185 -->|parfor 30| n187;
  n188 -->|parfor 2| n189;
  n188 -->|parfor 2| n190;
  n185 -->|parfor 2| n191;
  n185 -->|parfor 10| n192;
  n193 -->|parfor 2| n194;
  n193 -->|parfor 2| n195;
  n196 -->|parfor 2| n197;
  n196 -->|parfor 30| n198;
  n199 -->|parfor 2| n200;
  n199 -->|parfor 2| n201;
  n196 -->|parfor 2| n202;
  n196 -->|parfor 10| n203;
  n204 -->|parfor 2| n205;
  n204 -->|parfor 2| n206;
  n207 -->|parfor 2| n208;
  n207 -->|parfor 30| n209;
  n210 -->|parfor 2| n211;
  n210 -->|parfor 2| n212;
  n207 -->|parfor 2| n213;
  n207 -->|parfor 10| n214;
  n215 -->|parfor 2| n216;
  n215 -->|parfor 2| n217;
  n218 -->|parfor 2| n219;
  n218 -->|parfor 30| n220;
  n221 -->|parfor 2| n222;
  n221 -->|parfor 2| n223;
  n218 -->|parfor 2| n224;
  n218 -->|parfor 10| n225;
  n226 -->|parfor 2| n227;
  n226 -->|parfor 2| n228;
  n229 -->|parfor 2| n230;
  n229 -->|parfor 30| n231;
  n232 -->|parfor 2| n233;
  n232 -->|parfor 2| n234;
  n229 -->|parfor 2| n235;
  n229 -->|parfor 10| n236;
  n237 -->|parfor 2| n238;
  n237 -->|parfor 2| n239;
  n240 -->|parfor 2| n241;
  n240 -->|parfor 30| n242;
  n243 -->|parfor 2| n244;
  n243 -->|parfor 2| n245;
  n240 -->|parfor 2| n246;
  n240 -->|parfor 10| n247;
  n248 -->|parfor 2| n249;
  n248 -->|parfor 2| n250;
  n251 -->|parfor 2| n252;
  n251 -->|parfor 30| n253;
  n254 -->|parfor 2| n255;
  n254 -->|parfor 2| n256;
  n251 -->|parfor 2| n257;
  n251 -->|parfor 10| n258;
  n259 -->|parfor 2| n260;
  n259 -->|parfor 2| n261;
  n262 -->|parfor 2| n263;
  n262 -->|parfor 30| n264;
  n265 -->|parfor 2| n266;
  n265 -->|parfor 2| n267;
  n262 -->|parfor 2| n268;
  n262 -->|parfor 10| n269;
  n270 -->|parfor 2| n271;
  n270 -->|parfor 2| n272;
  n273 -->|parfor 2| n274;
  n273 -->|parfor 30| n275;
  n276 -->|parfor 2| n277;
  n276 -->|parfor 2| n278;
  n273 -->|parfor 2| n279;
  n273 -->|parfor 10| n280;
  n281 -->|parfor 2| n282;
  n281 -->|parfor 2| n283;
  n284 -->|parfor 2| n285;
  n284 -->|parfor 30| n286;
  n287 -->|parfor 2| n288;
  n287 -->|parfor 2| n289;
  n284 -->|parfor 2| n290;
  n284 -->|parfor 10| n291;
  n292 -->|parfor 2| n293;
  n292 -->|parfor 2| n294;
  n295 -->|parfor 2| n296;
  n295 -->|parfor 30| n297;
  n298 -->|parfor 2| n299;
  n298 -->|parfor 2| n300;
  n295 -->|parfor 2| n301;
  n295 -->|parfor 10| n302;
  n303 -->|parfor 2| n304;
  n303 -->|parfor 2| n305;
  n306 -->|parfor 2| n307;
  n306 -->|parfor 30| n308;
  n309 -->|parfor 2| n310;
  n309 -->|parfor 2| n311;
  n306 -->|parfor 2| n312;
  n306 -->|parfor 10| n313;
  n314 -->|parfor 2| n315;
  n314 -->|parfor 2| n316;
  n317 -->|parfor 2| n318;
  n317 -->|parfor 30| n319;
  n320 -->|parfor 2| n321;
  n320 -->|parfor 2| n322;
  n317 -->|parfor 2| n323;
  n317 -->|parfor 10| n324;
  n325 -->|parfor 2| n326;
  n325 -->|parfor 2| n327;
  n328 -->|parfor 2| n329;
  n328 -->|parfor 30| n330;
  n331 -->|parfor 2| n332;
  n331 -->|parfor 2| n333;
  n328 -->|parfor 2| n334;
  n328 -->|parfor 10| n335;
  n336 -->|parfor 2| n337;
  n336 -->|parfor 2| n338;
  n339 -->|parfor 2| n340;
  n339 -->|parfor 30| n341;
  n342 -->|parfor 2| n343;
  n342 -->|parfor 2| n344;
  n339 -->|parfor 2| n345;
  n339 -->|parfor 10| n346;
  n347 -->|parfor 2| n348;
  n347 -->|parfor 2| n349;
  n350 -->|parfor 2| n351;
  n350 -->|parfor 30| n352;
  n353 -->|parfor 2| n354;
  n353 -->|parfor 2| n355;
  n350 -->|parfor 2| n356;
  n350 -->|parfor 10| n357;
  n358 -->|parfor 2| n359;
  n358 -->|parfor 2| n360;
  n361 -->|parfor 2| n362;
  n361 -->|parfor 30| n363;
  n364 -->|parfor 2| n365;
  n364 -->|parfor 2| n366;
  n361 -->|parfor 2| n367;
  n361 -->|parfor 10| n368;
  n369 -->|parfor 2| n370;
  n369 -->|parfor 2| n371;
  n372 -->|parfor 2| n373;
  n372 -->|parfor 30| n374;
  n375 -->|parfor 2| n376;
  n375 -->|parfor 2| n377;
  n372 -->|parfor 2| n378;
  n372 -->|parfor 10| n379;
  n380 -->|parfor 2| n381;
  n380 -->|parfor 2| n382;
  n383 -->|parfor 2| n384;
  n383 -->|parfor 30| n385;
  n386 -->|parfor 2| n387;
  n386 -->|parfor 2| n388;
  n383 -->|parfor 2| n389;
  n383 -->|parfor 10| n390;
  n391 -->|parfor 2| n392;
  n391 -->|parfor 2| n393;
  n394 -->|parfor 2| n395;
  n394 -->|parfor 30| n396;
  n397 -->|parfor 2| n398;
  n397 -->|parfor 2| n399;
  n394 -->|parfor 2| n400;
  n394 -->|parfor 10| n401;
  n402 -->|parfor 2| n403;
  n402 -->|parfor 2| n404;
  n405 -->|parfor 2| n406;
  n405 -->|parfor 30| n407;
  n408 -->|parfor 2| n409;
  n408 -->|parfor 2| n410;
  n405 -->|parfor 2| n411;
  n405 -->|parfor 10| n412;
  n413 -->|parfor 2| n414;
  n413 -->|parfor 2| n415;
  n416 -->|parfor 8| n417;
  n416 -->|parfor 55| n418;
  n419 -->|parfor 17| n420;
  n416 -->|parfor 8| n421;
  n416 -->|parfor 5| n422;
  n423 -->|parfor 8| n424;
  n423 -->|parfor 57| n425;
  n426 -->|parfor 17| n427;
  n423 -->|parfor 8| n428;
  n423 -->|parfor 418| n429;
  n430 -->|parfor 8| n431;
  n430 -->|parfor 320| n432;
  n430 -->|parfor 5| n433;
  n434 -->|parfor 8| n435;
  n434 -->|parfor 59| n436;
  n437 -->|parfor 17| n438;
  n434 -->|parfor 8| n439;
  n434 -->|parfor 406| n440;
  n441 -->|parfor 8| n442;
  n441 -->|parfor 310| n443;
  n441 -->|parfor 5| n444;
  n445 -->|parfor 8| n446;
  n445 -->|parfor 61| n447;
  n448 -->|parfor 17| n449;
  n445 -->|parfor 8| n450;
  n445 -->|parfor 412| n451;
  n452 -->|parfor 8| n453;
  n452 -->|parfor 315| n454;
  n452 -->|parfor 5| n455;
  n456 -->|parfor 8| n457;
  n456 -->|parfor 63| n458;
  n459 -->|parfor 17| n460;
  n456 -->|parfor 8| n461;
  n456 -->|parfor 418| n462;
  n463 -->|parfor 8| n464;
  n463 -->|parfor 320| n465;
  n463 -->|parfor 5| n466;
  n467 -->|parfor 8| n468;
  n467 -->|parfor 65| n469;
  n470 -->|parfor 17| n471;
  n467 -->|parfor 8| n472;
  n467 -->|parfor 418| n473;
  n474 -->|parfor 8| n475;
  n474 -->|parfor 320| n476;
  n474 -->|parfor 5| n477;
  n478 -->|parfor 8| n479;
  n478 -->|parfor 67| n480;
  n481 -->|parfor 17| n482;
  n478 -->|parfor 8| n483;
  n478 -->|parfor 418| n484;
  n485 -->|parfor 8| n486;
  n485 -->|parfor 320| n487;
  n485 -->|parfor 5| n488;
  n489 -->|parfor 8| n490;
  n489 -->|parfor 69| n491;
  n492 -->|parfor 17| n493;
  n489 -->|parfor 8| n494;
  n489 -->|parfor 418| n495;
  n496 -->|parfor 8| n497;
  n496 -->|parfor 320| n498;
  n496 -->|parfor 5| n499;
  n500 -->|parfor 8| n501;
  n500 -->|parfor 71| n502;
  n503 -->|parfor 17| n504;
  n500 -->|parfor 8| n505;
  n500 -->|parfor 412| n506;
  n507 -->|parfor 8| n508;
  n507 -->|parfor 315| n509;
  n507 -->|parfor 5| n510;
  n511 -->|parfor 8| n512;
  n511 -->|parfor 73| n513;
  n514 -->|parfor 17| n515;
  n511 -->|parfor 8| n516;
  n511 -->|parfor 418| n517;
  n518 -->|parfor 8| n519;
  n518 -->|parfor 320| n520;
  n518 -->|parfor 5| n521;
  n522 -->|parfor 8| n523;
  n522 -->|parfor 75| n524;
  n525 -->|parfor 17| n526;
  n522 -->|parfor 8| n527;
  n522 -->|parfor 418| n528;
  n529 -->|parfor 8| n530;
  n529 -->|parfor 320| n531;
  n529 -->|parfor 5| n532;
  n533 -->|parfor 8| n534;
  n533 -->|parfor 77| n535;
  n536 -->|parfor 17| n537;
  n533 -->|parfor 8| n538;
  n533 -->|parfor 418| n539;
  n540 -->|parfor 8| n541;
  n540 -->|parfor 320| n542;
  n540 -->|parfor 5| n543;
  n1 -->|parfor 4| n544;
  n544 -->|parfor 2| n545;
  n1 -->|parfor 52| n147;
  n1 -->|parfor 2| n546;
  n1 -->|parfor 2| n547;
  n548 -->|parfor 30| n549;
  n549 -->|parfor 4| n550;
  n548 -->|parfor 2| n551;
  n548 -->|parfor 1152| n150;
  n552 -->|parfor 2| n553;
  n1["ImageEncoderViT @ sam_model"];
  n2["Block @ sam_model.blocks.[0-11]"];
  n3["Block @ sam_model.blocks.0"];
  n4["LayerNorm @ sam_model.blocks.[0-0].norm1"];
  n5["Attention @ sam_model.blocks.[0-0].attn"];
  n6["Attention @ sam_model.blocks.0.attn"];
  n7["Linear @ sam_model.blocks.[0-0].attn.qkv"];
  n8["Linear @ sam_model.blocks.[0-0].attn.proj"];
  n9["LayerNorm @ sam_model.blocks.[0-0].norm2"];
  n10["MLPBlock @ sam_model.blocks.[0-0].mlp"];
  n11["MLPBlock @ sam_model.blocks.0.mlp"];
  n12["Linear @ sam_model.blocks.[0-0].mlp.lin1"];
  n13["GELU @ sam_model.blocks.[0-0].mlp.act"];
  n14["Linear @ sam_model.blocks.[0-0].mlp.lin2"];
  n15["Block @ sam_model.blocks.1"];
  n16["LayerNorm @ sam_model.blocks.[1-1].norm1"];
  n17["Attention @ sam_model.blocks.[1-1].attn"];
  n18["Attention @ sam_model.blocks.1.attn"];
  n19["Linear @ sam_model.blocks.[1-1].attn.qkv"];
  n20["Linear @ sam_model.blocks.[1-1].attn.proj"];
  n21["LayerNorm @ sam_model.blocks.[1-1].norm2"];
  n22["MLPBlock @ sam_model.blocks.[1-1].mlp"];
  n23["MLPBlock @ sam_model.blocks.1.mlp"];
  n24["Linear @ sam_model.blocks.[1-1].mlp.lin1"];
  n25["GELU @ sam_model.blocks.[1-1].mlp.act"];
  n26["Linear @ sam_model.blocks.[1-1].mlp.lin2"];
  n27["Block @ sam_model.blocks.2"];
  n28["LayerNorm @ sam_model.blocks.[2-2].norm1"];
  n29["Attention @ sam_model.blocks.[2-2].attn"];
  n30["Attention @ sam_model.blocks.2.attn"];
  n31["Linear @ sam_model.blocks.[2-2].attn.qkv"];
  n32["Linear @ sam_model.blocks.[2-2].attn.proj"];
  n33["LayerNorm @ sam_model.blocks.[2-2].norm2"];
  n34["MLPBlock @ sam_model.blocks.[2-2].mlp"];
  n35["MLPBlock @ sam_model.blocks.2.mlp"];
  n36["Linear @ sam_model.blocks.[2-2].mlp.lin1"];
  n37["GELU @ sam_model.blocks.[2-2].mlp.act"];
  n38["Linear @ sam_model.blocks.[2-2].mlp.lin2"];
  n39["Block @ sam_model.blocks.3"];
  n40["LayerNorm @ sam_model.blocks.[3-3].norm1"];
  n41["Attention @ sam_model.blocks.[3-3].attn"];
  n42["Attention @ sam_model.blocks.3.attn"];
  n43["Linear @ sam_model.blocks.[3-3].attn.qkv"];
  n44["Linear @ sam_model.blocks.[3-3].attn.proj"];
  n45["LayerNorm @ sam_model.blocks.[3-3].norm2"];
  n46["MLPBlock @ sam_model.blocks.[3-3].mlp"];
  n47["MLPBlock @ sam_model.blocks.3.mlp"];
  n48["Linear @ sam_model.blocks.[3-3].mlp.lin1"];
  n49["GELU @ sam_model.blocks.[3-3].mlp.act"];
  n50["Linear @ sam_model.blocks.[3-3].mlp.lin2"];
  n51["Block @ sam_model.blocks.4"];
  n52["LayerNorm @ sam_model.blocks.[4-4].norm1"];
  n53["Attention @ sam_model.blocks.[4-4].attn"];
  n54["Attention @ sam_model.blocks.4.attn"];
  n55["Linear @ sam_model.blocks.[4-4].attn.qkv"];
  n56["Linear @ sam_model.blocks.[4-4].attn.proj"];
  n57["LayerNorm @ sam_model.blocks.[4-4].norm2"];
  n58["MLPBlock @ sam_model.blocks.[4-4].mlp"];
  n59["MLPBlock @ sam_model.blocks.4.mlp"];
  n60["Linear @ sam_model.blocks.[4-4].mlp.lin1"];
  n61["GELU @ sam_model.blocks.[4-4].mlp.act"];
  n62["Linear @ sam_model.blocks.[4-4].mlp.lin2"];
  n63["Block @ sam_model.blocks.5"];
  n64["LayerNorm @ sam_model.blocks.[5-5].norm1"];
  n65["Attention @ sam_model.blocks.[5-5].attn"];
  n66["Attention @ sam_model.blocks.5.attn"];
  n67["Linear @ sam_model.blocks.[5-5].attn.qkv"];
  n68["Linear @ sam_model.blocks.[5-5].attn.proj"];
  n69["LayerNorm @ sam_model.blocks.[5-5].norm2"];
  n70["MLPBlock @ sam_model.blocks.[5-5].mlp"];
  n71["MLPBlock @ sam_model.blocks.5.mlp"];
  n72["Linear @ sam_model.blocks.[5-5].mlp.lin1"];
  n73["GELU @ sam_model.blocks.[5-5].mlp.act"];
  n74["Linear @ sam_model.blocks.[5-5].mlp.lin2"];
  n75["Block @ sam_model.blocks.6"];
  n76["LayerNorm @ sam_model.blocks.[6-6].norm1"];
  n77["Attention @ sam_model.blocks.[6-6].attn"];
  n78["Attention @ sam_model.blocks.6.attn"];
  n79["Linear @ sam_model.blocks.[6-6].attn.qkv"];
  n80["Linear @ sam_model.blocks.[6-6].attn.proj"];
  n81["LayerNorm @ sam_model.blocks.[6-6].norm2"];
  n82["MLPBlock @ sam_model.blocks.[6-6].mlp"];
  n83["MLPBlock @ sam_model.blocks.6.mlp"];
  n84["Linear @ sam_model.blocks.[6-6].mlp.lin1"];
  n85["GELU @ sam_model.blocks.[6-6].mlp.act"];
  n86["Linear @ sam_model.blocks.[6-6].mlp.lin2"];
  n87["Block @ sam_model.blocks.7"];
  n88["LayerNorm @ sam_model.blocks.[7-7].norm1"];
  n89["Attention @ sam_model.blocks.[7-7].attn"];
  n90["Attention @ sam_model.blocks.7.attn"];
  n91["Linear @ sam_model.blocks.[7-7].attn.qkv"];
  n92["Linear @ sam_model.blocks.[7-7].attn.proj"];
  n93["LayerNorm @ sam_model.blocks.[7-7].norm2"];
  n94["MLPBlock @ sam_model.blocks.[7-7].mlp"];
  n95["MLPBlock @ sam_model.blocks.7.mlp"];
  n96["Linear @ sam_model.blocks.[7-7].mlp.lin1"];
  n97["GELU @ sam_model.blocks.[7-7].mlp.act"];
  n98["Linear @ sam_model.blocks.[7-7].mlp.lin2"];
  n99["Block @ sam_model.blocks.8"];
  n100["LayerNorm @ sam_model.blocks.[8-8].norm1"];
  n101["Attention @ sam_model.blocks.[8-8].attn"];
  n102["Attention @ sam_model.blocks.8.attn"];
  n103["Linear @ sam_model.blocks.[8-8].attn.qkv"];
  n104["Linear @ sam_model.blocks.[8-8].attn.proj"];
  n105["LayerNorm @ sam_model.blocks.[8-8].norm2"];
  n106["MLPBlock @ sam_model.blocks.[8-8].mlp"];
  n107["MLPBlock @ sam_model.blocks.8.mlp"];
  n108["Linear @ sam_model.blocks.[8-8].mlp.lin1"];
  n109["GELU @ sam_model.blocks.[8-8].mlp.act"];
  n110["Linear @ sam_model.blocks.[8-8].mlp.lin2"];
  n111["Block @ sam_model.blocks.9"];
  n112["LayerNorm @ sam_model.blocks.[9-9].norm1"];
  n113["Attention @ sam_model.blocks.[9-9].attn"];
  n114["Attention @ sam_model.blocks.9.attn"];
  n115["Linear @ sam_model.blocks.[9-9].attn.qkv"];
  n116["Linear @ sam_model.blocks.[9-9].attn.proj"];
  n117["LayerNorm @ sam_model.blocks.[9-9].norm2"];
  n118["MLPBlock @ sam_model.blocks.[9-9].mlp"];
  n119["MLPBlock @ sam_model.blocks.9.mlp"];
  n120["Linear @ sam_model.blocks.[9-9].mlp.lin1"];
  n121["GELU @ sam_model.blocks.[9-9].mlp.act"];
  n122["Linear @ sam_model.blocks.[9-9].mlp.lin2"];
  n123["Block @ sam_model.blocks.10"];
  n124["LayerNorm @ sam_model.blocks.[10-10].norm1"];
  n125["Attention @ sam_model.blocks.[10-10].attn"];
  n126["Attention @ sam_model.blocks.10.attn"];
  n127["Linear @ sam_model.blocks.[10-10].attn.qkv"];
  n128["Linear @ sam_model.blocks.[10-10].attn.proj"];
  n129["LayerNorm @ sam_model.blocks.[10-10].norm2"];
  n130["MLPBlock @ sam_model.blocks.[10-10].mlp"];
  n131["MLPBlock @ sam_model.blocks.10.mlp"];
  n132["Linear @ sam_model.blocks.[10-10].mlp.lin1"];
  n133["GELU @ sam_model.blocks.[10-10].mlp.act"];
  n134["Linear @ sam_model.blocks.[10-10].mlp.lin2"];
  n135["Block @ sam_model.blocks.11"];
  n136["LayerNorm @ sam_model.blocks.[11-11].norm1"];
  n137["Attention @ sam_model.blocks.[11-11].attn"];
  n138["Attention @ sam_model.blocks.11.attn"];
  n139["Linear @ sam_model.blocks.[11-11].attn.qkv"];
  n140["Linear @ sam_model.blocks.[11-11].attn.proj"];
  n141["LayerNorm @ sam_model.blocks.[11-11].norm2"];
  n142["MLPBlock @ sam_model.blocks.[11-11].mlp"];
  n143["MLPBlock @ sam_model.blocks.11.mlp"];
  n144["Linear @ sam_model.blocks.[11-11].mlp.lin1"];
  n145["GELU @ sam_model.blocks.[11-11].mlp.act"];
  n146["Linear @ sam_model.blocks.[11-11].mlp.lin2"];
  n147["Sequential @ sam_model.neck"];
  n148["Conv2d @ sam_model.neck.[0,2]"];
  n149["LayerNorm2d @ sam_model.neck.[1,3]"];
  n150["NoTPTransformer @ vision_model.transformer"];
  n151["NoTPTransformerBlock @ vision_model.transformer.layers.[0-23]"];
  n152["NoTPTransformerBlock @ vision_model.transformer.layers.0"];
  n153["LayerNorm @ vision_model.transformer.layers.[0-0].layer_norm1"];
  n154["NoTPAttention @ vision_model.transformer.layers.[0-0].self_attn"];
  n155["NoTPAttention @ vision_model.transformer.layers.0.self_attn"];
  n156["Linear @ vision_model.transformer.layers.[0-0].self_attn.qkv_proj"];
  n157["Linear @ vision_model.transformer.layers.[0-0].self_attn.out_proj"];
  n158["LayerNorm @ vision_model.transformer.layers.[0-0].layer_norm2"];
  n159["NoTPFeedForward @ vision_model.transformer.layers.[0-0].mlp"];
  n160["NoTPFeedForward @ vision_model.transformer.layers.0.mlp"];
  n161["Linear @ vision_model.transformer.layers.[0-0].mlp.fc1"];
  n162["Linear @ vision_model.transformer.layers.[0-0].mlp.fc2"];
  n163["NoTPTransformerBlock @ vision_model.transformer.layers.1"];
  n164["LayerNorm @ vision_model.transformer.layers.[1-1].layer_norm1"];
  n165["NoTPAttention @ vision_model.transformer.layers.[1-1].self_attn"];
  n166["NoTPAttention @ vision_model.transformer.layers.1.self_attn"];
  n167["Linear @ vision_model.transformer.layers.[1-1].self_attn.qkv_proj"];
  n168["Linear @ vision_model.transformer.layers.[1-1].self_attn.out_proj"];
  n169["LayerNorm @ vision_model.transformer.layers.[1-1].layer_norm2"];
  n170["NoTPFeedForward @ vision_model.transformer.layers.[1-1].mlp"];
  n171["NoTPFeedForward @ vision_model.transformer.layers.1.mlp"];
  n172["Linear @ vision_model.transformer.layers.[1-1].mlp.fc1"];
  n173["Linear @ vision_model.transformer.layers.[1-1].mlp.fc2"];
  n174["NoTPTransformerBlock @ vision_model.transformer.layers.2"];
  n175["LayerNorm @ vision_model.transformer.layers.[2-2].layer_norm1"];
  n176["NoTPAttention @ vision_model.transformer.layers.[2-2].self_attn"];
  n177["NoTPAttention @ vision_model.transformer.layers.2.self_attn"];
  n178["Linear @ vision_model.transformer.layers.[2-2].self_attn.qkv_proj"];
  n179["Linear @ vision_model.transformer.layers.[2-2].self_attn.out_proj"];
  n180["LayerNorm @ vision_model.transformer.layers.[2-2].layer_norm2"];
  n181["NoTPFeedForward @ vision_model.transformer.layers.[2-2].mlp"];
  n182["NoTPFeedForward @ vision_model.transformer.layers.2.mlp"];
  n183["Linear @ vision_model.transformer.layers.[2-2].mlp.fc1"];
  n184["Linear @ vision_model.transformer.layers.[2-2].mlp.fc2"];
  n185["NoTPTransformerBlock @ vision_model.transformer.layers.3"];
  n186["LayerNorm @ vision_model.transformer.layers.[3-3].layer_norm1"];
  n187["NoTPAttention @ vision_model.transformer.layers.[3-3].self_attn"];
  n188["NoTPAttention @ vision_model.transformer.layers.3.self_attn"];
  n189["Linear @ vision_model.transformer.layers.[3-3].self_attn.qkv_proj"];
  n190["Linear @ vision_model.transformer.layers.[3-3].self_attn.out_proj"];
  n191["LayerNorm @ vision_model.transformer.layers.[3-3].layer_norm2"];
  n192["NoTPFeedForward @ vision_model.transformer.layers.[3-3].mlp"];
  n193["NoTPFeedForward @ vision_model.transformer.layers.3.mlp"];
  n194["Linear @ vision_model.transformer.layers.[3-3].mlp.fc1"];
  n195["Linear @ vision_model.transformer.layers.[3-3].mlp.fc2"];
  n196["NoTPTransformerBlock @ vision_model.transformer.layers.4"];
  n197["LayerNorm @ vision_model.transformer.layers.[4-4].layer_norm1"];
  n198["NoTPAttention @ vision_model.transformer.layers.[4-4].self_attn"];
  n199["NoTPAttention @ vision_model.transformer.layers.4.self_attn"];
  n200["Linear @ vision_model.transformer.layers.[4-4].self_attn.qkv_proj"];
  n201["Linear @ vision_model.transformer.layers.[4-4].self_attn.out_proj"];
  n202["LayerNorm @ vision_model.transformer.layers.[4-4].layer_norm2"];
  n203["NoTPFeedForward @ vision_model.transformer.layers.[4-4].mlp"];
  n204["NoTPFeedForward @ vision_model.transformer.layers.4.mlp"];
  n205["Linear @ vision_model.transformer.layers.[4-4].mlp.fc1"];
  n206["Linear @ vision_model.transformer.layers.[4-4].mlp.fc2"];
  n207["NoTPTransformerBlock @ vision_model.transformer.layers.5"];
  n208["LayerNorm @ vision_model.transformer.layers.[5-5].layer_norm1"];
  n209["NoTPAttention @ vision_model.transformer.layers.[5-5].self_attn"];
  n210["NoTPAttention @ vision_model.transformer.layers.5.self_attn"];
  n211["Linear @ vision_model.transformer.layers.[5-5].self_attn.qkv_proj"];
  n212["Linear @ vision_model.transformer.layers.[5-5].self_attn.out_proj"];
  n213["LayerNorm @ vision_model.transformer.layers.[5-5].layer_norm2"];
  n214["NoTPFeedForward @ vision_model.transformer.layers.[5-5].mlp"];
  n215["NoTPFeedForward @ vision_model.transformer.layers.5.mlp"];
  n216["Linear @ vision_model.transformer.layers.[5-5].mlp.fc1"];
  n217["Linear @ vision_model.transformer.layers.[5-5].mlp.fc2"];
  n218["NoTPTransformerBlock @ vision_model.transformer.layers.6"];
  n219["LayerNorm @ vision_model.transformer.layers.[6-6].layer_norm1"];
  n220["NoTPAttention @ vision_model.transformer.layers.[6-6].self_attn"];
  n221["NoTPAttention @ vision_model.transformer.layers.6.self_attn"];
  n222["Linear @ vision_model.transformer.layers.[6-6].self_attn.qkv_proj"];
  n223["Linear @ vision_model.transformer.layers.[6-6].self_attn.out_proj"];
  n224["LayerNorm @ vision_model.transformer.layers.[6-6].layer_norm2"];
  n225["NoTPFeedForward @ vision_model.transformer.layers.[6-6].mlp"];
  n226["NoTPFeedForward @ vision_model.transformer.layers.6.mlp"];
  n227["Linear @ vision_model.transformer.layers.[6-6].mlp.fc1"];
  n228["Linear @ vision_model.transformer.layers.[6-6].mlp.fc2"];
  n229["NoTPTransformerBlock @ vision_model.transformer.layers.7"];
  n230["LayerNorm @ vision_model.transformer.layers.[7-7].layer_norm1"];
  n231["NoTPAttention @ vision_model.transformer.layers.[7-7].self_attn"];
  n232["NoTPAttention @ vision_model.transformer.layers.7.self_attn"];
  n233["Linear @ vision_model.transformer.layers.[7-7].self_attn.qkv_proj"];
  n234["Linear @ vision_model.transformer.layers.[7-7].self_attn.out_proj"];
  n235["LayerNorm @ vision_model.transformer.layers.[7-7].layer_norm2"];
  n236["NoTPFeedForward @ vision_model.transformer.layers.[7-7].mlp"];
  n237["NoTPFeedForward @ vision_model.transformer.layers.7.mlp"];
  n238["Linear @ vision_model.transformer.layers.[7-7].mlp.fc1"];
  n239["Linear @ vision_model.transformer.layers.[7-7].mlp.fc2"];
  n240["NoTPTransformerBlock @ vision_model.transformer.layers.8"];
  n241["LayerNorm @ vision_model.transformer.layers.[8-8].layer_norm1"];
  n242["NoTPAttention @ vision_model.transformer.layers.[8-8].self_attn"];
  n243["NoTPAttention @ vision_model.transformer.layers.8.self_attn"];
  n244["Linear @ vision_model.transformer.layers.[8-8].self_attn.qkv_proj"];
  n245["Linear @ vision_model.transformer.layers.[8-8].self_attn.out_proj"];
  n246["LayerNorm @ vision_model.transformer.layers.[8-8].layer_norm2"];
  n247["NoTPFeedForward @ vision_model.transformer.layers.[8-8].mlp"];
  n248["NoTPFeedForward @ vision_model.transformer.layers.8.mlp"];
  n249["Linear @ vision_model.transformer.layers.[8-8].mlp.fc1"];
  n250["Linear @ vision_model.transformer.layers.[8-8].mlp.fc2"];
  n251["NoTPTransformerBlock @ vision_model.transformer.layers.9"];
  n252["LayerNorm @ vision_model.transformer.layers.[9-9].layer_norm1"];
  n253["NoTPAttention @ vision_model.transformer.layers.[9-9].self_attn"];
  n254["NoTPAttention @ vision_model.transformer.layers.9.self_attn"];
  n255["Linear @ vision_model.transformer.layers.[9-9].self_attn.qkv_proj"];
  n256["Linear @ vision_model.transformer.layers.[9-9].self_attn.out_proj"];
  n257["LayerNorm @ vision_model.transformer.layers.[9-9].layer_norm2"];
  n258["NoTPFeedForward @ vision_model.transformer.layers.[9-9].mlp"];
  n259["NoTPFeedForward @ vision_model.transformer.layers.9.mlp"];
  n260["Linear @ vision_model.transformer.layers.[9-9].mlp.fc1"];
  n261["Linear @ vision_model.transformer.layers.[9-9].mlp.fc2"];
  n262["NoTPTransformerBlock @ vision_model.transformer.layers.10"];
  n263["LayerNorm @ vision_model.transformer.layers.[10-10].layer_norm1"];
  n264["NoTPAttention @ vision_model.transformer.layers.[10-10].self_attn"];
  n265["NoTPAttention @ vision_model.transformer.layers.10.self_attn"];
  n266["Linear @ vision_model.transformer.layers.[10-10].self_attn.qkv_proj"];
  n267["Linear @ vision_model.transformer.layers.[10-10].self_attn.out_proj"];
  n268["LayerNorm @ vision_model.transformer.layers.[10-10].layer_norm2"];
  n269["NoTPFeedForward @ vision_model.transformer.layers.[10-10].mlp"];
  n270["NoTPFeedForward @ vision_model.transformer.layers.10.mlp"];
  n271["Linear @ vision_model.transformer.layers.[10-10].mlp.fc1"];
  n272["Linear @ vision_model.transformer.layers.[10-10].mlp.fc2"];
  n273["NoTPTransformerBlock @ vision_model.transformer.layers.11"];
  n274["LayerNorm @ vision_model.transformer.layers.[11-11].layer_norm1"];
  n275["NoTPAttention @ vision_model.transformer.layers.[11-11].self_attn"];
  n276["NoTPAttention @ vision_model.transformer.layers.11.self_attn"];
  n277["Linear @ vision_model.transformer.layers.[11-11].self_attn.qkv_proj"];
  n278["Linear @ vision_model.transformer.layers.[11-11].self_attn.out_proj"];
  n279["LayerNorm @ vision_model.transformer.layers.[11-11].layer_norm2"];
  n280["NoTPFeedForward @ vision_model.transformer.layers.[11-11].mlp"];
  n281["NoTPFeedForward @ vision_model.transformer.layers.11.mlp"];
  n282["Linear @ vision_model.transformer.layers.[11-11].mlp.fc1"];
  n283["Linear @ vision_model.transformer.layers.[11-11].mlp.fc2"];
  n284["NoTPTransformerBlock @ vision_model.transformer.layers.12"];
  n285["LayerNorm @ vision_model.transformer.layers.[12-12].layer_norm1"];
  n286["NoTPAttention @ vision_model.transformer.layers.[12-12].self_attn"];
  n287["NoTPAttention @ vision_model.transformer.layers.12.self_attn"];
  n288["Linear @ vision_model.transformer.layers.[12-12].self_attn.qkv_proj"];
  n289["Linear @ vision_model.transformer.layers.[12-12].self_attn.out_proj"];
  n290["LayerNorm @ vision_model.transformer.layers.[12-12].layer_norm2"];
  n291["NoTPFeedForward @ vision_model.transformer.layers.[12-12].mlp"];
  n292["NoTPFeedForward @ vision_model.transformer.layers.12.mlp"];
  n293["Linear @ vision_model.transformer.layers.[12-12].mlp.fc1"];
  n294["Linear @ vision_model.transformer.layers.[12-12].mlp.fc2"];
  n295["NoTPTransformerBlock @ vision_model.transformer.layers.13"];
  n296["LayerNorm @ vision_model.transformer.layers.[13-13].layer_norm1"];
  n297["NoTPAttention @ vision_model.transformer.layers.[13-13].self_attn"];
  n298["NoTPAttention @ vision_model.transformer.layers.13.self_attn"];
  n299["Linear @ vision_model.transformer.layers.[13-13].self_attn.qkv_proj"];
  n300["Linear @ vision_model.transformer.layers.[13-13].self_attn.out_proj"];
  n301["LayerNorm @ vision_model.transformer.layers.[13-13].layer_norm2"];
  n302["NoTPFeedForward @ vision_model.transformer.layers.[13-13].mlp"];
  n303["NoTPFeedForward @ vision_model.transformer.layers.13.mlp"];
  n304["Linear @ vision_model.transformer.layers.[13-13].mlp.fc1"];
  n305["Linear @ vision_model.transformer.layers.[13-13].mlp.fc2"];
  n306["NoTPTransformerBlock @ vision_model.transformer.layers.14"];
  n307["LayerNorm @ vision_model.transformer.layers.[14-14].layer_norm1"];
  n308["NoTPAttention @ vision_model.transformer.layers.[14-14].self_attn"];
  n309["NoTPAttention @ vision_model.transformer.layers.14.self_attn"];
  n310["Linear @ vision_model.transformer.layers.[14-14].self_attn.qkv_proj"];
  n311["Linear @ vision_model.transformer.layers.[14-14].self_attn.out_proj"];
  n312["LayerNorm @ vision_model.transformer.layers.[14-14].layer_norm2"];
  n313["NoTPFeedForward @ vision_model.transformer.layers.[14-14].mlp"];
  n314["NoTPFeedForward @ vision_model.transformer.layers.14.mlp"];
  n315["Linear @ vision_model.transformer.layers.[14-14].mlp.fc1"];
  n316["Linear @ vision_model.transformer.layers.[14-14].mlp.fc2"];
  n317["NoTPTransformerBlock @ vision_model.transformer.layers.15"];
  n318["LayerNorm @ vision_model.transformer.layers.[15-15].layer_norm1"];
  n319["NoTPAttention @ vision_model.transformer.layers.[15-15].self_attn"];
  n320["NoTPAttention @ vision_model.transformer.layers.15.self_attn"];
  n321["Linear @ vision_model.transformer.layers.[15-15].self_attn.qkv_proj"];
  n322["Linear @ vision_model.transformer.layers.[15-15].self_attn.out_proj"];
  n323["LayerNorm @ vision_model.transformer.layers.[15-15].layer_norm2"];
  n324["NoTPFeedForward @ vision_model.transformer.layers.[15-15].mlp"];
  n325["NoTPFeedForward @ vision_model.transformer.layers.15.mlp"];
  n326["Linear @ vision_model.transformer.layers.[15-15].mlp.fc1"];
  n327["Linear @ vision_model.transformer.layers.[15-15].mlp.fc2"];
  n328["NoTPTransformerBlock @ vision_model.transformer.layers.16"];
  n329["LayerNorm @ vision_model.transformer.layers.[16-16].layer_norm1"];
  n330["NoTPAttention @ vision_model.transformer.layers.[16-16].self_attn"];
  n331["NoTPAttention @ vision_model.transformer.layers.16.self_attn"];
  n332["Linear @ vision_model.transformer.layers.[16-16].self_attn.qkv_proj"];
  n333["Linear @ vision_model.transformer.layers.[16-16].self_attn.out_proj"];
  n334["LayerNorm @ vision_model.transformer.layers.[16-16].layer_norm2"];
  n335["NoTPFeedForward @ vision_model.transformer.layers.[16-16].mlp"];
  n336["NoTPFeedForward @ vision_model.transformer.layers.16.mlp"];
  n337["Linear @ vision_model.transformer.layers.[16-16].mlp.fc1"];
  n338["Linear @ vision_model.transformer.layers.[16-16].mlp.fc2"];
  n339["NoTPTransformerBlock @ vision_model.transformer.layers.17"];
  n340["LayerNorm @ vision_model.transformer.layers.[17-17].layer_norm1"];
  n341["NoTPAttention @ vision_model.transformer.layers.[17-17].self_attn"];
  n342["NoTPAttention @ vision_model.transformer.layers.17.self_attn"];
  n343["Linear @ vision_model.transformer.layers.[17-17].self_attn.qkv_proj"];
  n344["Linear @ vision_model.transformer.layers.[17-17].self_attn.out_proj"];
  n345["LayerNorm @ vision_model.transformer.layers.[17-17].layer_norm2"];
  n346["NoTPFeedForward @ vision_model.transformer.layers.[17-17].mlp"];
  n347["NoTPFeedForward @ vision_model.transformer.layers.17.mlp"];
  n348["Linear @ vision_model.transformer.layers.[17-17].mlp.fc1"];
  n349["Linear @ vision_model.transformer.layers.[17-17].mlp.fc2"];
  n350["NoTPTransformerBlock @ vision_model.transformer.layers.18"];
  n351["LayerNorm @ vision_model.transformer.layers.[18-18].layer_norm1"];
  n352["NoTPAttention @ vision_model.transformer.layers.[18-18].self_attn"];
  n353["NoTPAttention @ vision_model.transformer.layers.18.self_attn"];
  n354["Linear @ vision_model.transformer.layers.[18-18].self_attn.qkv_proj"];
  n355["Linear @ vision_model.transformer.layers.[18-18].self_attn.out_proj"];
  n356["LayerNorm @ vision_model.transformer.layers.[18-18].layer_norm2"];
  n357["NoTPFeedForward @ vision_model.transformer.layers.[18-18].mlp"];
  n358["NoTPFeedForward @ vision_model.transformer.layers.18.mlp"];
  n359["Linear @ vision_model.transformer.layers.[18-18].mlp.fc1"];
  n360["Linear @ vision_model.transformer.layers.[18-18].mlp.fc2"];
  n361["NoTPTransformerBlock @ vision_model.transformer.layers.19"];
  n362["LayerNorm @ vision_model.transformer.layers.[19-19].layer_norm1"];
  n363["NoTPAttention @ vision_model.transformer.layers.[19-19].self_attn"];
  n364["NoTPAttention @ vision_model.transformer.layers.19.self_attn"];
  n365["Linear @ vision_model.transformer.layers.[19-19].self_attn.qkv_proj"];
  n366["Linear @ vision_model.transformer.layers.[19-19].self_attn.out_proj"];
  n367["LayerNorm @ vision_model.transformer.layers.[19-19].layer_norm2"];
  n368["NoTPFeedForward @ vision_model.transformer.layers.[19-19].mlp"];
  n369["NoTPFeedForward @ vision_model.transformer.layers.19.mlp"];
  n370["Linear @ vision_model.transformer.layers.[19-19].mlp.fc1"];
  n371["Linear @ vision_model.transformer.layers.[19-19].mlp.fc2"];
  n372["NoTPTransformerBlock @ vision_model.transformer.layers.20"];
  n373["LayerNorm @ vision_model.transformer.layers.[20-20].layer_norm1"];
  n374["NoTPAttention @ vision_model.transformer.layers.[20-20].self_attn"];
  n375["NoTPAttention @ vision_model.transformer.layers.20.self_attn"];
  n376["Linear @ vision_model.transformer.layers.[20-20].self_attn.qkv_proj"];
  n377["Linear @ vision_model.transformer.layers.[20-20].self_attn.out_proj"];
  n378["LayerNorm @ vision_model.transformer.layers.[20-20].layer_norm2"];
  n379["NoTPFeedForward @ vision_model.transformer.layers.[20-20].mlp"];
  n380["NoTPFeedForward @ vision_model.transformer.layers.20.mlp"];
  n381["Linear @ vision_model.transformer.layers.[20-20].mlp.fc1"];
  n382["Linear @ vision_model.transformer.layers.[20-20].mlp.fc2"];
  n383["NoTPTransformerBlock @ vision_model.transformer.layers.21"];
  n384["LayerNorm @ vision_model.transformer.layers.[21-21].layer_norm1"];
  n385["NoTPAttention @ vision_model.transformer.layers.[21-21].self_attn"];
  n386["NoTPAttention @ vision_model.transformer.layers.21.self_attn"];
  n387["Linear @ vision_model.transformer.layers.[21-21].self_attn.qkv_proj"];
  n388["Linear @ vision_model.transformer.layers.[21-21].self_attn.out_proj"];
  n389["LayerNorm @ vision_model.transformer.layers.[21-21].layer_norm2"];
  n390["NoTPFeedForward @ vision_model.transformer.layers.[21-21].mlp"];
  n391["NoTPFeedForward @ vision_model.transformer.layers.21.mlp"];
  n392["Linear @ vision_model.transformer.layers.[21-21].mlp.fc1"];
  n393["Linear @ vision_model.transformer.layers.[21-21].mlp.fc2"];
  n394["NoTPTransformerBlock @ vision_model.transformer.layers.22"];
  n395["LayerNorm @ vision_model.transformer.layers.[22-22].layer_norm1"];
  n396["NoTPAttention @ vision_model.transformer.layers.[22-22].self_attn"];
  n397["NoTPAttention @ vision_model.transformer.layers.22.self_attn"];
  n398["Linear @ vision_model.transformer.layers.[22-22].self_attn.qkv_proj"];
  n399["Linear @ vision_model.transformer.layers.[22-22].self_attn.out_proj"];
  n400["LayerNorm @ vision_model.transformer.layers.[22-22].layer_norm2"];
  n401["NoTPFeedForward @ vision_model.transformer.layers.[22-22].mlp"];
  n402["NoTPFeedForward @ vision_model.transformer.layers.22.mlp"];
  n403["Linear @ vision_model.transformer.layers.[22-22].mlp.fc1"];
  n404["Linear @ vision_model.transformer.layers.[22-22].mlp.fc2"];
  n405["NoTPTransformerBlock @ vision_model.transformer.layers.23"];
  n406["LayerNorm @ vision_model.transformer.layers.[23-23].layer_norm1"];
  n407["NoTPAttention @ vision_model.transformer.layers.[23-23].self_attn"];
  n408["NoTPAttention @ vision_model.transformer.layers.23.self_attn"];
  n409["Linear @ vision_model.transformer.layers.[23-23].self_attn.qkv_proj"];
  n410["Linear @ vision_model.transformer.layers.[23-23].self_attn.out_proj"];
  n411["LayerNorm @ vision_model.transformer.layers.[23-23].layer_norm2"];
  n412["NoTPFeedForward @ vision_model.transformer.layers.[23-23].mlp"];
  n413["NoTPFeedForward @ vision_model.transformer.layers.23.mlp"];
  n414["Linear @ vision_model.transformer.layers.[23-23].mlp.fc1"];
  n415["Linear @ vision_model.transformer.layers.[23-23].mlp.fc2"];
  n416["DeepseekV2DecoderLayer @ layers.0"];
  n417["DeepseekV2RMSNorm @ layers.[0-0].input_layernorm"];
  n418["LlamaAttention @ layers.[0-0].self_attn"];
  n419["LlamaAttention @ layers.0.self_attn"];
  n420["LlamaRotaryEmbedding @ layers.[0-0].self_attn.rotary_emb"];
  n421["DeepseekV2RMSNorm @ layers.[0-0].post_attention_layernorm"];
  n422["DeepseekV2MLP @ layers.[0-0].mlp"];
  n423["DeepseekV2DecoderLayer @ layers.1"];
  n424["DeepseekV2RMSNorm @ layers.[1-1].input_layernorm"];
  n425["LlamaAttention @ layers.[1-1].self_attn"];
  n426["LlamaAttention @ layers.1.self_attn"];
  n427["LlamaRotaryEmbedding @ layers.[1-1].self_attn.rotary_emb"];
  n428["DeepseekV2RMSNorm @ layers.[1-1].post_attention_layernorm"];
  n429["DeepseekV2MoE @ layers.[1-1].mlp"];
  n430["DeepseekV2MoE @ layers.1.mlp"];
  n431["MoEGate @ layers.[1-1].mlp.gate"];
  n432["DeepseekV2MLP @ layers.1.mlp.experts.[0-63]"];
  n433["DeepseekV2MLP @ layers.[1-1].mlp.shared_experts"];
  n434["DeepseekV2DecoderLayer @ layers.2"];
  n435["DeepseekV2RMSNorm @ layers.[2-2].input_layernorm"];
  n436["LlamaAttention @ layers.[2-2].self_attn"];
  n437["LlamaAttention @ layers.2.self_attn"];
  n438["LlamaRotaryEmbedding @ layers.[2-2].self_attn.rotary_emb"];
  n439["DeepseekV2RMSNorm @ layers.[2-2].post_attention_layernorm"];
  n440["DeepseekV2MoE @ layers.[2-2].mlp"];
  n441["DeepseekV2MoE @ layers.2.mlp"];
  n442["MoEGate @ layers.[2-2].mlp.gate"];
  n443["DeepseekV2MLP @ layers.2.mlp.experts.[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,59,60,61,62,63]"];
  n444["DeepseekV2MLP @ layers.[2-2].mlp.shared_experts"];
  n445["DeepseekV2DecoderLayer @ layers.3"];
  n446["DeepseekV2RMSNorm @ layers.[3-3].input_layernorm"];
  n447["LlamaAttention @ layers.[3-3].self_attn"];
  n448["LlamaAttention @ layers.3.self_attn"];
  n449["LlamaRotaryEmbedding @ layers.[3-3].self_attn.rotary_emb"];
  n450["DeepseekV2RMSNorm @ layers.[3-3].post_attention_layernorm"];
  n451["DeepseekV2MoE @ layers.[3-3].mlp"];
  n452["DeepseekV2MoE @ layers.3.mlp"];
  n453["MoEGate @ layers.[3-3].mlp.gate"];
  n454["DeepseekV2MLP @ layers.3.mlp.experts.[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,54,55,56,57,58,59,60,61,62,63]"];
  n455["DeepseekV2MLP @ layers.[3-3].mlp.shared_experts"];
  n456["DeepseekV2DecoderLayer @ layers.4"];
  n457["DeepseekV2RMSNorm @ layers.[4-4].input_layernorm"];
  n458["LlamaAttention @ layers.[4-4].self_attn"];
  n459["LlamaAttention @ layers.4.self_attn"];
  n460["LlamaRotaryEmbedding @ layers.[4-4].self_attn.rotary_emb"];
  n461["DeepseekV2RMSNorm @ layers.[4-4].post_attention_layernorm"];
  n462["DeepseekV2MoE @ layers.[4-4].mlp"];
  n463["DeepseekV2MoE @ layers.4.mlp"];
  n464["MoEGate @ layers.[4-4].mlp.gate"];
  n465["DeepseekV2MLP @ layers.4.mlp.experts.[0-63]"];
  n466["DeepseekV2MLP @ layers.[4-4].mlp.shared_experts"];
  n467["DeepseekV2DecoderLayer @ layers.5"];
  n468["DeepseekV2RMSNorm @ layers.[5-5].input_layernorm"];
  n469["LlamaAttention @ layers.[5-5].self_attn"];
  n470["LlamaAttention @ layers.5.self_attn"];
  n471["LlamaRotaryEmbedding @ layers.[5-5].self_attn.rotary_emb"];
  n472["DeepseekV2RMSNorm @ layers.[5-5].post_attention_layernorm"];
  n473["DeepseekV2MoE @ layers.[5-5].mlp"];
  n474["DeepseekV2MoE @ layers.5.mlp"];
  n475["MoEGate @ layers.[5-5].mlp.gate"];
  n476["DeepseekV2MLP @ layers.5.mlp.experts.[0-63]"];
  n477["DeepseekV2MLP @ layers.[5-5].mlp.shared_experts"];
  n478["DeepseekV2DecoderLayer @ layers.6"];
  n479["DeepseekV2RMSNorm @ layers.[6-6].input_layernorm"];
  n480["LlamaAttention @ layers.[6-6].self_attn"];
  n481["LlamaAttention @ layers.6.self_attn"];
  n482["LlamaRotaryEmbedding @ layers.[6-6].self_attn.rotary_emb"];
  n483["DeepseekV2RMSNorm @ layers.[6-6].post_attention_layernorm"];
  n484["DeepseekV2MoE @ layers.[6-6].mlp"];
  n485["DeepseekV2MoE @ layers.6.mlp"];
  n486["MoEGate @ layers.[6-6].mlp.gate"];
  n487["DeepseekV2MLP @ layers.6.mlp.experts.[0-63]"];
  n488["DeepseekV2MLP @ layers.[6-6].mlp.shared_experts"];
  n489["DeepseekV2DecoderLayer @ layers.7"];
  n490["DeepseekV2RMSNorm @ layers.[7-7].input_layernorm"];
  n491["LlamaAttention @ layers.[7-7].self_attn"];
  n492["LlamaAttention @ layers.7.self_attn"];
  n493["LlamaRotaryEmbedding @ layers.[7-7].self_attn.rotary_emb"];
  n494["DeepseekV2RMSNorm @ layers.[7-7].post_attention_layernorm"];
  n495["DeepseekV2MoE @ layers.[7-7].mlp"];
  n496["DeepseekV2MoE @ layers.7.mlp"];
  n497["MoEGate @ layers.[7-7].mlp.gate"];
  n498["DeepseekV2MLP @ layers.7.mlp.experts.[0-63]"];
  n499["DeepseekV2MLP @ layers.[7-7].mlp.shared_experts"];
  n500["DeepseekV2DecoderLayer @ layers.8"];
  n501["DeepseekV2RMSNorm @ layers.[8-8].input_layernorm"];
  n502["LlamaAttention @ layers.[8-8].self_attn"];
  n503["LlamaAttention @ layers.8.self_attn"];
  n504["LlamaRotaryEmbedding @ layers.[8-8].self_attn.rotary_emb"];
  n505["DeepseekV2RMSNorm @ layers.[8-8].post_attention_layernorm"];
  n506["DeepseekV2MoE @ layers.[8-8].mlp"];
  n507["DeepseekV2MoE @ layers.8.mlp"];
  n508["MoEGate @ layers.[8-8].mlp.gate"];
  n509["DeepseekV2MLP @ layers.8.mlp.experts.[0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63]"];
  n510["DeepseekV2MLP @ layers.[8-8].mlp.shared_experts"];
  n511["DeepseekV2DecoderLayer @ layers.9"];
  n512["DeepseekV2RMSNorm @ layers.[9-9].input_layernorm"];
  n513["LlamaAttention @ layers.[9-9].self_attn"];
  n514["LlamaAttention @ layers.9.self_attn"];
  n515["LlamaRotaryEmbedding @ layers.[9-9].self_attn.rotary_emb"];
  n516["DeepseekV2RMSNorm @ layers.[9-9].post_attention_layernorm"];
  n517["DeepseekV2MoE @ layers.[9-9].mlp"];
  n518["DeepseekV2MoE @ layers.9.mlp"];
  n519["MoEGate @ layers.[9-9].mlp.gate"];
  n520["DeepseekV2MLP @ layers.9.mlp.experts.[0-63]"];
  n521["DeepseekV2MLP @ layers.[9-9].mlp.shared_experts"];
  n522["DeepseekV2DecoderLayer @ layers.10"];
  n523["DeepseekV2RMSNorm @ layers.[10-10].input_layernorm"];
  n524["LlamaAttention @ layers.[10-10].self_attn"];
  n525["LlamaAttention @ layers.10.self_attn"];
  n526["LlamaRotaryEmbedding @ layers.[10-10].self_attn.rotary_emb"];
  n527["DeepseekV2RMSNorm @ layers.[10-10].post_attention_layernorm"];
  n528["DeepseekV2MoE @ layers.[10-10].mlp"];
  n529["DeepseekV2MoE @ layers.10.mlp"];
  n530["MoEGate @ layers.[10-10].mlp.gate"];
  n531["DeepseekV2MLP @ layers.10.mlp.experts.[0-63]"];
  n532["DeepseekV2MLP @ layers.[10-10].mlp.shared_experts"];
  n533["DeepseekV2DecoderLayer @ layers.11"];
  n534["DeepseekV2RMSNorm @ layers.[11-11].input_layernorm"];
  n535["LlamaAttention @ layers.[11-11].self_attn"];
  n536["LlamaAttention @ layers.11.self_attn"];
  n537["LlamaRotaryEmbedding @ layers.[11-11].self_attn.rotary_emb"];
  n538["DeepseekV2RMSNorm @ layers.[11-11].post_attention_layernorm"];
  n539["DeepseekV2MoE @ layers.[11-11].mlp"];
  n540["DeepseekV2MoE @ layers.11.mlp"];
  n541["MoEGate @ layers.[11-11].mlp.gate"];
  n542["DeepseekV2MLP @ layers.11.mlp.experts.[0-63]"];
  n543["DeepseekV2MLP @ layers.[11-11].mlp.shared_experts"];
  n544["PatchEmbed @ sam_model.patch_embed"];
  n545["Conv2d @ sam_model.patch_embed.proj"];
  n546["Conv2d @ sam_model.net_2"];
  n547["Conv2d @ sam_model.net_3"];
  n548["VitModel @ vision_model"];
  n549["CLIPVisionEmbeddings @ vision_model.embeddings"];
  n550["Embedding @ vision_model.embeddings.position_embedding"];
  n551["LayerNorm @ vision_model.pre_layrnorm"];
  n552["MlpProjector @ projector"];
  n553["Linear @ projector.layers"];